### ISSUE TITLE
I have errors when running main.py  (I installed all the requirements) and i think it's because of the cairoSVG module

### ISSUE THREAD

**Issue by superscratch444tre** [Secret-chest/scratch2python#13]
I have errors when running main.py  (I installed all the requirements)
Please help me find the solution.

**Screenshots**
<img width="201" alt="The code" src="https://user-images.githubusercontent.com/69812464/152635020-4bdc8d5d-bc11-4d86-83cb-d1b01cd062f2.png">
<img width="856" alt="The errors" src="https://user-images.githubusercontent.com/69812464/152635068-0ee9846f-5e56-4390-9e0f-ca22dfbb6cef.png">
The project code: [gotomouseforever.zip](https://github.com/Secret-chest/scratch2python/files/8007672/gotomouseforever.zip)

</div>

**Comment by Secret-chest** [comment]
The project code does not matter. We use CairoSVG for loading SVGs.

It might be because you are on windows.
CairoSVG documentation says:
> on Windows, you’ll have to install Visual C++ compiler for Python and Cairo
Links: https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.x_with_Visual_Studio_2022_.28x86.2C_x64.2C_ARM.2C_ARM64.29

I can't really help out with that any more. Last time I used Windows was 1 year ago, but if you have any more issues, please reply.

**Comment by superscratch444tre** [comment]
> The project code does not matter. We use CairoSVG for loading SVGs.
> 
> It might be because you are on windows. CairoSVG documentation says:
> 
> > on Windows, you’ll have to install Visual C++ compiler for Python and Cairo
> > Links: https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.x_with_Visual_Studio_2022_.28x86.2C_x64.2C_ARM.2C_ARM64.29
> 
> I can't really help out with that any more. Last time I used Windows was 1 year ago, but if you have any more issues, please reply.

I have installed it with the instructions from that link but it is still the same. There are the same errors.

**Comment by Secret-chest** [comment]
> > The project code does not matter. We use CairoSVG for loading SVGs.
> > 
> > It might be because you are on windows. CairoSVG documentation says:
> > 
> > > on Windows, you’ll have to install Visual C++ compiler for Python and Cairo
> > > Links: https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.x_with_Visual_Studio_2022_.28x86.2C_x64.2C_ARM.2C_ARM64.29
> > 
> > I can't really help out with that any more. Last time I used Windows was 1 year ago, but if you have any more issues, please reply.
> 
> I have installed it with the instructions from that link but it is still the same. There are the same errors.

Could you look up "python cairoSVG windows" on Google?

**Comment by superscratch444tre** [comment]
I have found the solution. The cairo libraries were missing. I have created a "cairolibs" folder in the scratch2python folder, where I put all the cairo-related libraries. Now it works. I can create a pull request to add this change for the windows users, if you want.

**Comment by Secret-chest** [comment]
> I have found the solution. The cairo libraries were missing. I have created a "cairolibs" folder in the scratch2python folder, where I put all the cairo-related libraries. Now it works. I can create a pull request to add this change for the windows users, if you want.

Yes, sure. Send it.
