### ISSUE TITLE
New errors when running main.py

### ISSUE THREAD

**Issue by superscratch444tre** [Secret-chest/scratch2python#16]
**Screenshots**
<img width="774" alt="image" src="https://user-images.githubusercontent.com/69812464/152841509-ab046089-75fe-47ef-a1c4-2c8cfdf960d1.png">

**Comment by Secret-chest** [comment]
Try this:
`pip install pydirectory`

**Comment by superscratch444tre** [comment]
> Try this: `pip install pydirectory`

Still the same....

**Comment by Secret-chest** [comment]
> > Try this: `pip install pydirectory`
> 
> Still the same....

Ok. It's because Python dosen't have permission to delete files (which is needed for removing the old project data).

**Comment by Secret-chest** [comment]
![image](https://user-images.githubusercontent.com/74449186/152843512-feab1f9d-b7c7-4240-b351-e62f8b245cd2.png)
Uncheck this.

**Comment by superscratch444tre** [comment]
Resolved! It was because of the folder where s2p was located.

**Comment by superscratch444tre** [comment]
Now it works well. 
<img width="356" alt="image" src="https://user-images.githubusercontent.com/69812464/152843636-53bb74c4-0950-4abc-b5c6-657fb9119d63.png">

**Comment by Secret-chest** [comment]
> Now it works well. <img alt="image" width="356" src="https://user-images.githubusercontent.com/69812464/152843636-53bb74c4-0950-4abc-b5c6-657fb9119d63.png">

Good! Where did you install it now?

**Comment by superscratch444tre** [comment]
yes.

> > In the desktop folder.
> 
> Before it was im my documents?

**Comment by Secret-chest** [comment]
> yes.
> 
> > > In the desktop folder.
> > 
> > 
> > Before it was im my documents?

Great. I'll make a notice about it.
