### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by Melt2002** [Secret-chest/scratch2python#21]
Error:
```shell
Scratch2Python M13 (development version) running on linux
Loading project
DEBUG: New position (0, 0) set for sprite Stage
DEBUG: New position (240, 0) set for sprite test4
DEBUG: New position (0, 195.5) set for sprite test3
Extracting project
Traceback (most recent call last):
  File "main.py", line 156, in <module>
    class SizeDialog(tkinter.simpledialog.Dialog):
  File "main.py", line 160, in SizeDialog
    def body(self, master) -> tuple[str, str]:
TypeError: 'type' object is not subscriptable
```
I don't what else to say, but my config file uses the default options.

**Comment by Melt2002** [comment]
All requirements in requirements.txt are installed, and I am using M13.

**Comment by Secret-chest** [comment]
@Melt2002 You may be on a different timezone? I'm on GMT +2, +3 on DST, so if this came out at midnight you know why.

**Comment by Melt2002** [comment]
> I see linux. What distro do you use?

Zorin OS 16 Core, which is based off of Ubuntu 20.04

**Comment by Melt2002** [comment]
> @Melt2002 I pushed a commit. Does it work now?

Yep, whatever you did fixed it!
