### ISSUE TITLE
The translations don't display, only the name of the string is displayed

### ISSUE THREAD

**Issue by superscratch444tre** [Secret-chest/scratch2python#24]
**Describe the bug**
The translations do not display, only the name of the string apppears (I tried changing the language in the config.py file to **en** or **ro** and still the same thing)

**To Reproduce**
Open a project and see.

**Expected behavior**
The translations should appear.

**Screenshots**
<img width="860" alt="screenshot" src="https://user-images.githubusercontent.com/69812464/156875683-d623e637-b8cd-42f0-8922-008ccb791d46.png">

**Additional context**
OS-Windows 11
Python 3.9

**Comment by Secret-chest** [comment]
`pip install python-i18n`

**Comment by Secret-chest** [comment]
We have a new dependency

**Comment by superscratch444tre** [comment]
@Secret-chest  I have installed it, still the same.

**Comment by superscratch444tre** [comment]
<img width="815" alt="image" src="https://user-images.githubusercontent.com/69812464/156888759-5d92571a-c557-4784-8e3f-9dd4599cab49.png">

**Comment by superscratch444tre** [comment]
@Secret-chest

**Comment by Secret-chest** [comment]
@superscratch444tre Does it work now?

**Comment by superscratch444tre** [comment]
No.... 
<img width="861" alt="image" src="https://user-images.githubusercontent.com/69812464/156898530-75712dc7-2db7-4268-8796-46963f69d077.png">
@Secret-chest

**Comment by Secret-chest** [comment]
Did you update? Please use `git` to update.

**Comment by Secret-chest** [comment]
@superscratch444tre

**Comment by Secret-chest** [comment]
@superscratch444tre Show me:
* the contents of your `config.py` file
* your `lang` folder, if any
* the contents of the `en.yml` file

**Comment by superscratch444tre** [comment]
> @superscratch444tre Show me:
> 
> * the contents of your `config.py` file

![image](https://user-images.githubusercontent.com/69812464/156917561-5ebdbead-2177-4215-be6e-58120c99f6c0.png)
<img width="473" alt="image" src="https://user-images.githubusercontent.com/69812464/156917626-c45c197a-5a8a-4d73-b63c-3454b5dc5375.png">


> * your `lang` folder, if any

<img width="680" alt="image" src="https://user-images.githubusercontent.com/69812464/156917605-8641dd3e-8d24-45b3-b64a-837be3ea2dd4.png">


> * the contents of the `en.yml` file

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/69812464/156917670-4656a317-80ab-4bb7-8856-1db728f564e1.png">

@Secret-chest

**Comment by superscratch444tre** [comment]
@Secret-chest also, can you please reopen this issue?

**Comment by superscratch444tre** [comment]
Does not matter anymore, I made it work. On windows, you need to install `python-i18n[YAML]` (`pip install python-i18n[YAML]`), not just `python-i18n`. I can open a pull request to add a notice about this in the readme if you want.

**Comment by Secret-chest** [comment]
> Does not matter anymore, I made it work. On windows, you need to install `python-i18n[YAML]` (`pip install python-i18n[YAML]`), not just `python-i18n`. I can open a pull request to add a notice about this in the readme if you want. @Secret-chest 
> 
> ![image](https://user-images.githubusercontent.com/69812464/156919779-08667307-f215-4e5a-b5f7-85c62d8d03ea.png)
> 

Can you add [YAML] to requierments.txt?

You need to do it on Linux too. Forgot I installed it that way.
